# Generated by Django 2.0.1 on 2018-01-02 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180102_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 2, 18, 48, 57, 938445), verbose_name='创建时间'),
        ),
    ]
